# Use the official Python 3.11 image from the Docker Hub
FROM python:3.11-slim

# Set the working directory
WORKDIR /app

# Copy the requirements file into the containera
COPY requirements.txt .

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code into the container
COPY . .

# Install watchdog for hot-reloading
RUN pip install watchdog

# Expose the port the app runs on
EXPOSE 5000

# Define the command to run the application with hot-reloading
CMD ["python", "-m", "flask", "run", "--host=0.0.0.0", "--port=5000", "--reload"]
CMD ["python", "app.py", "--reload"]
