# Use the official Node.js 16 image as the base image
FROM node:16

# Create and change to the app directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies, including dev dependencies
RUN npm install

# Install nodemon and ts-node globally
RUN npm install -g nodemon ts-node

# Copy the rest of the application code
COPY . .

# Expose the application port
EXPOSE 3000

# Start the application with nodemon and ts-node
CMD ["nodemon", "--watch", "src", "--exec", "ts-node", "src/index.ts"]
