// Code generated by ent, DO NOT EDIT.

package attachmentref

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/notzree/uprank-backend/inference-backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AttachmentRef {
	return predicate.AttachmentRef(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AttachmentRef {
	return predicate.AttachmentRef(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AttachmentRef {
	return predicate.AttachmentRef(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AttachmentRef {
	return predicate.AttachmentRef(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AttachmentRef {
	return predicate.AttachmentRef(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AttachmentRef {
	return predicate.AttachmentRef(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AttachmentRef {
	return predicate.AttachmentRef(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AttachmentRef {
	return predicate.AttachmentRef(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AttachmentRef {
	return predicate.AttachmentRef(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.AttachmentRef {
	return predicate.AttachmentRef(sql.FieldEQ(FieldName, v))
}

// Link applies equality check predicate on the "link" field. It's identical to LinkEQ.
func Link(v string) predicate.AttachmentRef {
	return predicate.AttachmentRef(sql.FieldEQ(FieldLink, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.AttachmentRef {
	return predicate.AttachmentRef(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.AttachmentRef {
	return predicate.AttachmentRef(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.AttachmentRef {
	return predicate.AttachmentRef(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.AttachmentRef {
	return predicate.AttachmentRef(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.AttachmentRef {
	return predicate.AttachmentRef(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.AttachmentRef {
	return predicate.AttachmentRef(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.AttachmentRef {
	return predicate.AttachmentRef(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.AttachmentRef {
	return predicate.AttachmentRef(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.AttachmentRef {
	return predicate.AttachmentRef(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.AttachmentRef {
	return predicate.AttachmentRef(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.AttachmentRef {
	return predicate.AttachmentRef(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.AttachmentRef {
	return predicate.AttachmentRef(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.AttachmentRef {
	return predicate.AttachmentRef(sql.FieldContainsFold(FieldName, v))
}

// LinkEQ applies the EQ predicate on the "link" field.
func LinkEQ(v string) predicate.AttachmentRef {
	return predicate.AttachmentRef(sql.FieldEQ(FieldLink, v))
}

// LinkNEQ applies the NEQ predicate on the "link" field.
func LinkNEQ(v string) predicate.AttachmentRef {
	return predicate.AttachmentRef(sql.FieldNEQ(FieldLink, v))
}

// LinkIn applies the In predicate on the "link" field.
func LinkIn(vs ...string) predicate.AttachmentRef {
	return predicate.AttachmentRef(sql.FieldIn(FieldLink, vs...))
}

// LinkNotIn applies the NotIn predicate on the "link" field.
func LinkNotIn(vs ...string) predicate.AttachmentRef {
	return predicate.AttachmentRef(sql.FieldNotIn(FieldLink, vs...))
}

// LinkGT applies the GT predicate on the "link" field.
func LinkGT(v string) predicate.AttachmentRef {
	return predicate.AttachmentRef(sql.FieldGT(FieldLink, v))
}

// LinkGTE applies the GTE predicate on the "link" field.
func LinkGTE(v string) predicate.AttachmentRef {
	return predicate.AttachmentRef(sql.FieldGTE(FieldLink, v))
}

// LinkLT applies the LT predicate on the "link" field.
func LinkLT(v string) predicate.AttachmentRef {
	return predicate.AttachmentRef(sql.FieldLT(FieldLink, v))
}

// LinkLTE applies the LTE predicate on the "link" field.
func LinkLTE(v string) predicate.AttachmentRef {
	return predicate.AttachmentRef(sql.FieldLTE(FieldLink, v))
}

// LinkContains applies the Contains predicate on the "link" field.
func LinkContains(v string) predicate.AttachmentRef {
	return predicate.AttachmentRef(sql.FieldContains(FieldLink, v))
}

// LinkHasPrefix applies the HasPrefix predicate on the "link" field.
func LinkHasPrefix(v string) predicate.AttachmentRef {
	return predicate.AttachmentRef(sql.FieldHasPrefix(FieldLink, v))
}

// LinkHasSuffix applies the HasSuffix predicate on the "link" field.
func LinkHasSuffix(v string) predicate.AttachmentRef {
	return predicate.AttachmentRef(sql.FieldHasSuffix(FieldLink, v))
}

// LinkEqualFold applies the EqualFold predicate on the "link" field.
func LinkEqualFold(v string) predicate.AttachmentRef {
	return predicate.AttachmentRef(sql.FieldEqualFold(FieldLink, v))
}

// LinkContainsFold applies the ContainsFold predicate on the "link" field.
func LinkContainsFold(v string) predicate.AttachmentRef {
	return predicate.AttachmentRef(sql.FieldContainsFold(FieldLink, v))
}

// HasFreelancer applies the HasEdge predicate on the "freelancer" edge.
func HasFreelancer() predicate.AttachmentRef {
	return predicate.AttachmentRef(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, FreelancerTable, FreelancerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFreelancerWith applies the HasEdge predicate on the "freelancer" edge with a given conditions (other predicates).
func HasFreelancerWith(preds ...predicate.UpworkFreelancer) predicate.AttachmentRef {
	return predicate.AttachmentRef(func(s *sql.Selector) {
		step := newFreelancerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AttachmentRef) predicate.AttachmentRef {
	return predicate.AttachmentRef(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AttachmentRef) predicate.AttachmentRef {
	return predicate.AttachmentRef(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AttachmentRef) predicate.AttachmentRef {
	return predicate.AttachmentRef(sql.NotPredicates(p))
}
