services:
  server:
    image: notzree/uprank/uprank-backend/main-backend:1.0
    container_name: uprank-main-backend
    stdin_open: true
    tty: true
    ports:
      - ${EXPOSED_SERVER_PORT}:${EXPOSED_SERVER_PORT}
    build:
      context: ./main-backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./main-backend:/app
      - ~/.aws:/root/.aws
    environment:
      - MS_API_KEY=${MS_API_KEY}
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - SERVER_PORT=${SERVER_PORT}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - RANKING_QUEUE_URL=${RANKING_QUEUE_URL}
      - INFERENCE_SERVER_URL=${INFERENCE_SERVER_URL}
  inference-server:
    image: notzree/uprank/uprank-backend/inference-backend:1.0
    container_name: uprank-inference-backend
    stdin_open: true
    tty: true
    ports:
      - ${EXPOSED_INFERENCE_SERVER_PORT}:${EXPOSED_INFERENCE_SERVER_PORT}
    build:
      context: ./inference-backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./inference-backend:/app
    environment:
      - MS_API_KEY=${MS_API_KEY}
      - SERVER_PORT=${EXPOSED_INFERENCE_SERVER_PORT}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - MAIN_BACKEND_URL=${MAIN_BACKEND_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
  queue-handler:
    image: notzree/uprank/uprank-backend/queue-handler:1.0
    container_name: uprank-queue-handler
    stdin_open: true
    tty: true
    ports:
      - ${EXPOSED_QUEUE_HANDLER_PORT}:${EXPOSED_QUEUE_HANDLER_PORT}
    build:
      context: ./queue-handler
      dockerfile: Dockerfile.dev
    volumes:
      - ./queue-handler:/app
      - ~/.aws:/root/.aws
    environment:
      - MS_API_KEY=${MS_API_KEY}
      - SERVER_PORT=${EXPOSED_QUEUE_HANDLER_PORT}
      - RANKING_QUEUE_URL=${RANKING_QUEUE_URL}
      - MAIN_BACKEND_URL=${MAIN_BACKEND_URL}
      - INFERENCE_SERVER_URL=${INFERENCE_SERVER_URL}
      - NOTIFICATION_QUEUE_URL=${NOTIFICATION_QUEUE_URL}


