services:
  server:
    image: notzree/uprank/uprank-backend/main-backend:1.0
    container_name: uprank-main-backend
    stdin_open: true
    tty: true
    ports:
      - ${EXPOSED_SERVER_PORT}:${EXPOSED_SERVER_PORT}
    build:
      context: ./main-backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./main-backend:/app
      - ~/.aws:/root/.aws
    environment:
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - SERVER_PORT=${SERVER_PORT}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - SCRAPER_QUEUE_URL=${SCRAPER_QUEUE_URL}
  scraper_server:
    image: notzree/uprank/uprank-backend/scraper-backend:1.0
    container_name: uprank-scraper-backend
    stdin_open: true
    tty: true
    ports:
      - ${EXPOSED_SCRAPER_PORT}:${EXPOSED_SCRAPER_PORT}
    build:
      context: ./scraper-backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./scraper-backend:/app
      - ~/.aws:/root/.aws
    environment:
      - SCRAPER_PORT=${SCRAPER_PORT}
      - SCRAPER_QUEUE_URL=${SCRAPER_QUEUE_URL}


