name: Build Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

env:
  PULUMI_DEV_STACK_NAME: dev
  PULUMI_PROD_STACK_NAME: prod

jobs:
  build:
    name: Build and deploy backend infrastructure, including container images.
    runs-on: ubuntu-latest
    environment: dev # this is just the environment with all of the required variables.
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
      
      - name: "Set Environment Variables"
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "PULUMI_STACK_NAME=${PULUMI_PROD_STACK_NAME}" >> $GITHUB_ENV
          else
            echo "PULUMI_STACK_NAME=${PULUMI_DEV_STACK_NAME}" >> $GITHUB_ENV
          fi
      - name: "Set up Go"
        uses: actions/setup-go@v3
        with:
          go-version: 'stable'

      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ vars.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: "Install dependencies for queues"
        run: |
          cd backend/infrastructure/stack/queues
          go mod download

      - name: "Deploy queues stack"
        uses: pulumi/actions@v5
        with:
          work-dir: backend/infrastructure/stack/queues
          command: up
          stack-name: ${{ env.PULUMI_STACK_NAME }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: "Install dependencies for networking"
        working-directory: backend/infrastructure/stack/networking
        run: |
          go mod download

      - name: "Deploy networking stack"
        uses: pulumi/actions@v5
        with:
          work-dir: backend/infrastructure/stack/networking
          command: up
          stack-name: ${{ env.PULUMI_STACK_NAME }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: "Install dependencies for application-base"
        working-directory: backend/infrastructure/stack/application-base
        run: |
          go mod download

      - name: "Deploy application-base stack"
        uses: pulumi/actions@v5
        with:
          work-dir: backend/infrastructure/stack/application-base
          command: up
          stack-name: ${{ env.PULUMI_STACK_NAME }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: "Install dependencies for secrets"
        working-directory: backend/infrastructure/stack/secrets
        run: |
          go mod download

      - name: "Deploy secrets stack"
        uses: pulumi/actions@v5
        with:
          work-dir: backend/infrastructure/stack/secrets
          command: up
          stack-name: ${{ env.PULUMI_STACK_NAME }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: "Install dependencies for main-backend-image"
        working-directory: backend/infrastructure/stack/main-backend-image
        run: |
          go mod download

      - name: "Deploy main-backend-image stack"
        uses: pulumi/actions@v5
        with:
          work-dir: backend/infrastructure/stack/main-backend-image
          command: up
          stack-name: ${{ env.PULUMI_STACK_NAME }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: "Install dependencies for inference-backend-image"
        working-directory: backend/infrastructure/stack/inference-backend-image
        run: |
          go mod download

      - name: "Deploy inference-backend-image stack"
        uses: pulumi/actions@v5
        with:
          work-dir: backend/infrastructure/stack/inference-backend-image
          command: up
          stack-name: ${{ env.PULUMI_STACK_NAME }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: "Install dependencies for queue-handler-image"
        working-directory: backend/infrastructure/stack/queue-handler-image
        run: |
          go mod download

      - name: "Deploy queue-handler-image stack"
        uses: pulumi/actions@v5
        with:
          work-dir: backend/infrastructure/stack/queue-handler-image
          command: up
          stack-name: ${{ env.PULUMI_STACK_NAME }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
