name: Build app

on:
    push:
        branches:
        - production
        paths:
        - 'app/**'
    
env:
  PULUMI_DEV_STACK_NAME: dev
  PULUMI_PROD_STACK_NAME: prod

jobs:
    build:
        name: Build and deploy SST ION Next.js App
        runs-on: ubuntu-latest
        environment: dev
        steps:
            - name: "Checkout repository"
              uses: actions/checkout@v4
            - name: "Confiugre AWS Credentials"
              uses: aws-actions/configure-aws-credentials@v4
              with:
                    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    aws-region: ${{ vars.AWS_REGION }}
                    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            - name: "Set Environment Variables"
              run: |
                    if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
                    echo "PULUMI_STACK_NAME=${{env.PULUMI_PROD_STACK_NAME}}" >> $GITHUB_ENV
                    else
                    echo "PULUMI_STACK_NAME=${{env.PULUMI_DEV_STACK_NAME}}" >> $GITHUB_ENV
                    fi
            - name: "Extract backend url"
              working-directory: backend/infrastructure/stack/main-backend-image
              run: |
                    BACKEND_URL=$(pulumi stack output -s ${{ env.PULUMI_STACK_NAME }} main-backend-alb-url)
                    echo "BACKEND_URL=${BACKEND_URL}" >> $GITHUB_ENV
              env:
                PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
            - name: "Install dependencies"
              run: |
                    cd app
                    npm install
            - uses: croco-dev/setup-ion@v1
              with:
                version: latest
            - name: "Build app"
              working-directory: app
              run: |
                    sst deploy --stage production
              env:
                NODE_ENV: production
                NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ vars.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
                NEXT_PUBLIC_CLERK_SIGN_IN_URL: ${{ vars.NEXT_PUBLIC_CLERK_SIGN_IN_URL }}
                NEXT_PUBLIC_CLERK_SIGN_UP_URL: ${{ vars.NEXT_PUBLIC_CLERK_SIGN_UP_URL }}
                CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
                NEXT_PUBLIC_BACKEND_PROD_BASE_URL: ${{env.BACKEND_URL}}
