name: Build app

on:
    push:
        branches:
        - main
        paths:
        - 'app/**'
    
env:
  PULUMI_DEV_STACK_NAME: dev
  PULUMI_PROD_STACK_NAME: prod

jobs:
    build:
        name: Build and deploy SST ION Next.js App
        runs-on: ubuntu-latest
        environment: dev
        steps:
            - name: "Checkout repository"
              uses: actions/checkout@v4
            - name: "Confiugre AWS Credentials"
              uses: aws-actions/configure-aws-credentials@v4
              with:
                    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    aws-region: ${{ vars.AWS_REGION }}
                    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            - name: "Set Environment Variables"
              run: |
                    if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
                    echo "PULUMI_STACK_NAME=${{env.PULUMI_PROD_STACK_NAME}}" >> $GITHUB_ENV
                    else
                    echo "PULUMI_STACK_NAME=${{env.PULUMI_DEV_STACK_NAME}}" >> $GITHUB_ENV
                    fi
            - name: "Extract backend url"
              run: |
                    BACKEND_URL=$(pulumi stack output -s ${{ env.PULUMI_STACK_NAME }} main-backend-alb-url)
                    echo "BACKEND_URL=${BACKEND_URL}" >> $GITHUB_ENV
              env:
                PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
            - name: "Install dependencies"
              run: |
                    cd app
                    npm i
            - name: "Build app"
              run: |
                    cd app
                    NEXT_PUBLIC_BACKEND_DEV_BASE_URL=${{env.BACKEND_URL}} 
                    npx sst deploy

