name: Pulumi preview

on:
  pull_request:
    paths:
      - 'backend/infrastructure/stack/**'

env:
  PULUMI_DEV_STACK_NAME: dev
  PULUMI_PROD_STACK_NAME: prod

jobs:
    preview:
        name: Preview Pulumi Projects
        runs-on: ubuntu-latest
        environment: dev
        strategy:
            matrix:
                project:
                  - backend/infrastructure/stack/networking
                  - backend/infrastructure/stack/application-base
                  - backend/infrastructure/stack/queues
                  - backend/infrastructure/stack/secrets
                  - backend/infrastructure/stack/main-backend-image
                  - backend/infrastructure/stack/inference-backend-image
                  - backend/infrastructure/stack/queue-handler-image
        steps:
        - name: "Checkout repository"
          uses: actions/checkout@v4
        
        - name: "Set Environment Variables"
          run: |
            if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
              echo "PULUMI_STACK_NAME=$PULUMI_PROD_STACK_NAME" >> $GITHUB_ENV
            else
              echo "PULUMI_STACK_NAME=$PULUMI_DEV_STACK_NAME" >> $GITHUB_ENV
            fi

        - name: "Set up Go"
          uses: actions/setup-go@v3
          with:
            go-version: 'stable'

        - name: "Configure AWS Credentials"
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-region: ${{ vars.AWS_REGION }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        - name: "Install dependencies"
          run: |
            cd ${{ matrix.project }}
            go mod download
            
        - name: "Run Pulumi Preview"
          uses: pulumi/actions@v3
          with:
            command: preview
            stack-name: prod #todo: change to it to $PULUMI_STACK_NAME when we have enough money to pay for multiple environments
          env:    
            PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
